Repository codatio/codat-docs, pull requests merged in 2023-06, with the labels that each got.

#428 Allow CORS for RSS feed
  vercel.json
Labels: reviewed, ready to merge

#429 Allow Datadog headers
  vercel.json
Labels: reviewed, ready to merge

#436 Update faq-quickbooks-online.md
  docs/integrations/accounting/quickbooksonline/faq-quickbooks-online.md
Labels: review required

#441 Test client minor fix
  docs/bank-feeds-api/sage-bank-feeds/sage-bank-feeds-setup.md
Labels: review required

#444 add some deails about the rate limiting response to the docs
  docs/using-the-api/rate-limits.md
Labels: ready to merge

#460 add entry for deprecation re: new company synchronized webhook
  blog/231009-deprecation-webhooks-new-company-synchronized.md
  blog/authors.yml
Labels: ready to merge

#455 Homepage edits
  docs/index.mdx
Labels: review required

#464 Modified dates
  docs/using-the-api/modified-dates.md
  docs/using-the-api/optimizing-api-calls.md
Labels: review required

#457 Update accounting-xero-app-partner-guidance.md
  docs/integrations/accounting/xero/accounting-xero-app-partner-guidance.md
Labels: ready to merge

#403 Navigation restructuring
  docs/auth-flow/authorize-embedded-link.md
  docs/auth-flow/overview.md
  docs/configure/integrations.md
  docs/configure/plans/free.md
  docs/configure/products.md
  docs/core-concepts/companies.md
  docs/core-concepts/connections.md
  docs/core-concepts/data-type-settings.md
  docs/core-concepts/data-type.md
  docs/core-concepts/integrations.md
  docs/core-concepts/overview.md
  docs/get-started/overview.md
  docs/guides/overview.md
  docs/index.mdx
  docs/integrations/accounting/sage50/sage-50-requirements.md
  docs/introduction/create-account.md
  docs/introduction/libraries.md
  docs/introduction/migration.md
  docs/introduction/testing.md
  docs/other/developer-resources.md
  docs/other/portal/account-management.md
  docs/other/portal/companies.md
  docs/other/portal/dashboard.md
  docs/other/portal/dashboard.mdx
  docs/other/portal/developers.md
  docs/other/portal/pull-and-push-history.md
  docs/other/portal/usage-and-billing.md
  docs/other/user-management/sso.md
  docs/products/overview.mdx
  docs/usecases/bill-pay/bills.md
  docs/using-the-api/authentication.md
  docs/using-the-api/get-data.md
  docs/using-the-api/managing-companies.md
  docs/using-the-api/overview.md
  docs/using-the-api/pull-history.md
  docs/using-the-api/push.md
  docs/using-the-api/queueing-data-syncs.md
  package-lock.json
  package.json
  sidebars.js
  sidebars/authFlow.js
  sidebars/dataModel.js
  sidebars/integrations.js
  src/components/global/LocalStorageChecklist/index.js
  src/components/global/Products/index.js
  src/components/global/Usecases/index.js
  src/styles/components/_cards.scss
  src/styles/components/_checkbox.scss
  src/styles/components/_doc-sidebar.scss
  src/styles/components/_mermaid.scss
  src/styles/custom.scss
  src/theme/DocSidebarItem/index.js
  static/img/libraries/csharp.svg
  static/img/libraries/go.svg
  static/img/libraries/python.svg
  static/img/libraries/typescript.svg
  static/img/premium.svg
  static/img/sidebar/gear-fine.svg
  static/img/sidebar/user.svg
  static/img/sidebar/x-circle.svg
Labels: review required

#451 Embedded link enhancements - June 2023
  docs/auth-flow/authorize-embedded-link.md
  static/img/auth-flow/link-sdk_connection-status-error.png
Labels: review required

#489 Borders on images
  src/styles/components/_images.scss
Labels: changes needed
