Repository codatio/codat-docs, pull requests merged in 2023-08, with the labels that each got.

#635 Remove and edit pages containing categories v2
  docs/assess/categories/api-categorization-of-accounts.md
  docs/assess/categories/categories.md
  docs/assess/portal/categorization-of-accounts.md
  docs/assess/portal/categorize-accounts.md
  docs/assess/portal/overview.md
Labels: reviewed, comments

#644 xero-updates-july
  docs/integrations/accounting/xero/partner-certification/checkpoints-app-store.md
  docs/integrations/accounting/xero/partner-certification/checkpoints-lending.md
  docs/integrations/accounting/xero/partner-certification/scopes.md
  docs/integrations/accounting/xero/partner-certification/sign-up-with-xero.md
  static/img/integrations/accounting/xero/Sign-Up-with-Xero-Option-B-User-Flow.png
  static/img/integrations/accounting/xero/Sign-up-success-redirect.png
  static/img/integrations/accounting/xero/Xero-General-Lending.PNG
Labels: comments

#691 Minor typos fixes to S4C
  docs/commerce/error-documentation.md
  docs/commerce/overview.md
  docs/lending/excel/overview.md
Labels: DO NOT MERGE

#690 Fixed other bad urls
  docs/bank-feeds/data-types.md
  docs/bank-feeds/overview.mdx
  sidebars/bank-feeds.js
  src/components/global/Integrations/integrations.js
Labels: comments
