Repository codatio/codat-docs, pull requests merged in 2023-09, with the labels that each got.

#729 Lending API content rework
  docs/lending/data-types.md
  docs/lending/features/accounts-payable-overview.md
  docs/lending/features/accounts-receivable-overview.md
  docs/lending/features/bank-statements-overview.md
  docs/lending/features/company-info-overview.md
  docs/lending/features/excel-download-overview.md
  docs/lending/features/financial-statements-overview.md
  docs/lending/features/liabilities-overview.md
  docs/lending/features/sales-overview.md
  docs/lending/get-started.md
  docs/lending/guides/general-loan-writeback.md
  docs/lending/overview.md
  sidebars/lending.js
  src/components/global/Integrations/integrations.js
  static/img/lending/acct-categorization-v3-1.png
  static/img/lending/acct-categorization-v3-2.png
  static/img/lending/acct-categorization-v3-3.png
Labels: review required

#774 Update quickbooks-online-integration-reference.md
  docs/integrations/accounting/quickbooksonline/quickbooks-online-integration-reference.md
Labels: ready to merge

#783 Jasper bartlett xero bank feeds
  docs/integrations/accounting/xero/partner-certification/checkpoints-app-store.md
  docs/integrations/accounting/xero/partner-certification/checkpoints-bank-feeds.md
  docs/integrations/accounting/xero/partner-certification/checkpoints-lending.md
Labels: reviewed

#767 Adding glossary
  docs/get-started/first-steps.md
  docs/glossary.md
  docs/index.mdx
  docs/terms/account.md
  docs/terms/bill-payment.md
  docs/terms/bill.md
  docs/terms/company.md
  docs/terms/customer.md
  docs/terms/invoice.md
  docs/terms/journal.md
  docs/terms/supplier.md
  docusaurus.config.js
  package-lock.json
  package.json
  sidebars.js
  src/components/global/Glossary/Glossary.js
  src/components/global/Glossary/TermPreview.js
  src/components/global/Glossary/tooltip-styles.scss
Labels: DO NOT MERGE
