Repository codatio/codat-docs, pull requests merged in 2023-12, with the labels that each got.

#908 Added code snippets to lending
  docs/bank-feeds/setup.md
  docs/lending/features/accounts-payable-overview.md
  docs/lending/features/accounts-receivable-overview.md
  docs/lending/features/bank-statements-overview.md
  docs/lending/features/company-info-overview.md
  docs/lending/features/excel-download-overview.md
  docs/lending/features/financial-statements-overview.md
  docs/lending/features/liabilities-overview.md
  docs/lending/features/sales-overview.md
  docs/lending/get-started.md
  docs/lending/overview.md
  src/components/global/ClientLibraries/index.tsx
Labels: ready to merge

#911 Add enterprise sso content
  docs/enterprise/tech-overview/security/sso.md
Labels: comments

#915 Update faq.md
  docs/expenses/faq.md
Labels: ready to merge

#920 SfC Text Localisation
  docs/commerce/merchant-configuration.md
Labels: DO NOT MERGE, changes needed

#913 Payables - added code snippets
  docs/bank-feeds/create-account.md
  docs/payables/bills.md
  docs/payables/configure-customer.md
  docs/payables/get-started.md
  docs/payables/mapping.md
  docs/payables/overview.mdx
  docs/payables/payments.md
  docs/payables/suppliers.md
Labels: ready to merge

#933 Update introduction.md
  docs/lending/guides/loan-qualification/introduction.md
Labels: ready to merge
