Repository codatio/codat-docs, pull requests merged in 2023-03, with the labels that each got.

#217 Ensuring clear books always has a space
  docs/integrations/accounting/overview.md
  src/components/global/Integrations/integrations.js
Labels: reviewed, ready to merge

#216 58660: Adding 'description' to Company creation
  docs/core-concepts/companies.md
  docs/introduction/first-steps.md
  docs/using-the-api/managing-companies.md
Labels: review required

#195 Netsuite - delete Bills
  docs/integrations/accounting/netsuite/accounting-netsuite-delete-bill-payments.md
  docs/integrations/accounting/netsuite/accounting-netsuite-delete-bills-billpayments.md
  docs/integrations/accounting/netsuite/accounting-netsuite.md
  sidebars/integrations.js
  static/img/integrations/accounting/netsuite/netsuite_deposite-other-deposits.png
Labels: reviewed, ready to merge

#212 Update gettingstarted.md
  docs/sync-for-expenses/gettingstarted.md
Labels: ready to merge

#39 Use American English, add apostrophes and hyphens
  blog/230411-deletion-of-data.md
  docs/assess/categories/categories.md
  docs/assess/portal/overview.md
  docs/auth-flow/customize/customize-link.md
  docs/bank-feeds-api/overview.md
  docs/bank-feeds-api/qbo-bank-feeds/qbo-bank-feeds-setup.md
  docs/bank-feeds-api/sage-bank-feeds/sage-bank-feeds-authenticate-users-web-app.md
  docs/bank-feeds-api/sage-bank-feeds/sage-bank-feeds-setup.md
  docs/bank-feeds-api/sage-bank-feeds/sage-bank-feeds-use.md
  docs/index.mdx
  docs/integrations/accounting/netsuite/accounting-netsuite-setup.md
  docs/integrations/accounting/pandle/accounting-pandle-setup.md
  docs/integrations/accounting/quickbooksdesktop/install-qbd-connector-right-networks.md
  docs/integrations/accounting/quickbooksdesktop/quickbooks-desktop-troubleshooting.md
  docs/integrations/accounting/quickbooksonline/faq-quickbooks-online.md
  docs/integrations/accounting/sage-intacct/accounting-sage-intacct-setup.md
  docs/integrations/accounting/sage200/accounting-sage200-setup.md
  docs/integrations/accounting/xero/xero-app-partner-program.md
  docs/integrations/accounting/zoho-books/accounting-zohobooks-setup.md
  docs/integrations/banking/basiq/banking-basiq.md
  docs/integrations/banking/plaid/reauthorise-url-links.md
  docs/integrations/banking/plaid/switching-between-plaid-environments.md
  docs/integrations/banking/plaid/test-your-plaid-integration.md
  docs/integrations/commerce/bigcommerce/commerce-bigcommerce-test.md
  docs/integrations/commerce/clover/test-your-clover-integration.md
  docs/integrations/commerce/mollie/commerce-mollie-test.md
  docs/integrations/commerce/paypal/set-up-paypal-in-production.md
  docs/integrations/commerce/paypal/test-paypal.md
  docs/integrations/commerce/prestashop/test-prestashop.md
  docs/integrations/commerce/shopify/test-shopify.md
  docs/integrations/commerce/square/test-square.md
  docs/integrations/commerce/stripe/commerce-stripe.md
  docs/integrations/commerce/stripe/test-stripe.md
  docs/integrations/commerce/sumup/test-sumup-1.md
  docs/integrations/commerce/woocommerce/test-woocommerce.md
  docs/integrations/commerce/zettle/test-zettle.md
  docs/introduction/create-account.md
  docs/introduction/migration.md
  docs/introduction/webhooks/core-rules-create.md
  docs/introduction/webhooks/core-rules-webhooksecurity.md
  docs/other/portal/dashboard.md
  docs/sfc/build-with-sync-for-commerce/sync-platform-selection.md
  docs/sfc/sync-for-commerce-knowledge-base/sync-data-model.md
  docs/sync-for-expenses/sync-process/sync-process-explained.md
  docs/usecases/bank-feeds.md
  src/components/global/Api/index.css
Labels: changes needed

#220 Cleaning up SfC push data pages
  docs/sfc/build-with-sync-for-commerce/functional-examples-of-data.md
  docs/sfc/build-with-sync-for-commerce/implementing-codats-no-code-merchant-configuration.md
  docs/sfc/build-with-sync-for-commerce/sync-data-pushing.md
  docs/sfc/overview.md
  sidebars/sync-for-commerce.js
Labels: reviewed

#209 Underwriting demo links
  docs/assess/guides/underwriting/process-loan.md
  docs/assess/guides/underwriting/uw-decision.md
Labels: ready to merge

#218 First steps guide: code blocks into tabs
  docs/introduction/first-steps.md
Labels: review required

#188 Update URL to IAM User, Access Policy & Role
  docs/integrations/commerce/amazon-seller-central/amazon-registration-steps.md
Labels: reviewed, ready to merge

#224 Documenting 'Unknown' state of push status
  docs/using-the-api/push.md
Labels: review required

#221 Feat/recaps
  docs/using-the-api/authentication.md
  docs/using-the-api/errors.md
  docs/using-the-api/managing-companies.md
  docs/using-the-api/modified-dates.md
  docs/using-the-api/ordering-results.md
  docs/using-the-api/paging.md
  docs/using-the-api/push.md
  docs/using-the-api/queueing-data-syncs.md
  sidebars.js
Labels: reviewed, changes needed

#219 QBD: add note about separate admins
  docs/integrations/accounting/quickbooksdesktop/accounting-quickbooksdesktop.md
  docs/integrations/accounting/quickbooksdesktop/installing-the-quickbooks-connector.md
  docs/integrations/accounting/quickbooksdesktop/software-and-hardware-requirements.md
Labels: reviewed, ready to merge

#225 230710 Company metrics endpoint changelog
  blog/230710-deprecation-companies-metrics.md
Labels: review required

#226 Freeagent - Add call-outs for pushing Direct costs
  docs/integrations/accounting/freeagent/freeagent-integration-reference.md
Labels: reviewed, ready to merge

#227 Usage and billing dashboard
  docs/other/portal/dashboard.md
  docs/other/portal/usage-and-billing.md
  sidebars.js
  static/img/other-guides/0002-usage-billing-page.png
Labels: review required

#98 Assess docs
  docs/assess/categories/api-categorization-of-accounts.md
Labels: changes needed, conflicts

#231 added platform coverage for sync for expenses
  docs/sync-for-expenses/overview.md
  sidebars/sync-for-expenses.js
  src/components/global/Integrations/index.tsx
  src/components/global/Integrations/integrations.js
Labels: reviewed, changes needed

#233 Move scroll to top
  src/styles/custom.scss
Labels: ready to merge

#242 Fix: banking in auth flow and start-up billing
  docs/auth-flow/customize/customize-link.md
  docs/integrations/banking/overview.md
  docs/other/portal/usage-and-billing.md
Labels: review required

#243 Async use of Link
  docs/auth-flow/overview.md
Labels: review required

#246 Monitor auth flow
  docs/auth-flow/optimize/monitor-auth-flow.md
  sidebars/authFlow.js
  static/img/link/0002-auth-flow-monitor.png
Labels: review required

#245 Improve the Xero setup docs
  docs/integrations/accounting/xero/accounting-xero-setup.md
  static/img/integrations/accounting/xero/xero_app-client-secret-1-field-obscured.png
Labels: reviewed, ready to merge

#255 Feat/use case infrastructure
  docs/accounting-api/overview.md
  docs/assess/overview.md
  docs/bank-feeds-api/overview.mdx
  docs/banking-api/overview.md
  docs/commerce-api/overview.md
  docs/index.mdx
  docs/sfc/overview.md
  docs/sync-for-expenses/overview.md
  docs/usecases/bank-feeds/bank-feeds.md
  docs/usecases/overview.md
  docs/usecases/summary/automating-payables.md
  docs/usecases/summary/automating-receivables.md
  docs/usecases/summary/dashboarding.md
  docs/usecases/summary/integrating-commerce-data.md
  docs/usecases/summary/managing-expenses.md
  docs/usecases/summary/managing-payroll.md
  docs/usecases/summary/reconciling-bank-transactions.md
  docs/usecases/summary/underwriting.md
  sidebars.js
  src/components/global/PageHeader/index.js
  src/components/global/PageHeader/styles.module.scss
  src/styles/components/_cards.scss
  src/styles/components/_doc-sidebar.scss
  src/styles/components/_video.scss
  static/img/sidebar/usecase.svg
  static/img/use-cases/summary-pages/6c7b9e84-bank-reconciliation.png
  static/img/use-cases/summary-pages/75fd84ed-commerce-data.png
  static/img/use-cases/summary-pages/795ecc39-managing-expenses.png
  static/img/use-cases/summary-pages/982cf32b-fpa-dashboarding.png
  static/img/use-cases/summary-pages/d0c6b0b7-automating-payables.png
  static/img/use-cases/summary-pages/dbdaea6d-underwriting.png
  static/img/use-cases/summary-pages/fad7ec95-4automating-receivables.png
  static/logos/products/Accounting.svg
  static/logos/products/Assess.svg
  static/logos/products/BankFeeds.svg
  static/logos/products/Banking.svg
  static/logos/products/Commerce.svg
  static/logos/products/SyncforCommerce.svg
  static/logos/products/SyncforExpenses.svg
  static/logos/usecases/accounts-payable.svg
  static/logos/usecases/accounts-receivable.svg
  static/logos/usecases/company-info.svg
  static/logos/usecases/dashboarding.svg
  static/logos/usecases/lending.svg
  static/logos/usecases/payments.svg
  static/logos/usecases/payroll.svg
  static/logos/usecases/pull-push.svg
  static/logos/usecases/sandbox.svg
  static/logos/usecases/sync-commerce.svg
  static/logos/usecases/sync-expenses.svg
  static/logos/usecases/sync.svg
Labels: DO NOT MERGE

#259 Changelog template change
  blog/240101-draft.md
Labels: review required

#262 Fix couple of links
  docs/index.mdx
Labels: review required

#265 Docs compare with Readme.io
  docs/assess/data-integrity/api-data-integrity.md
  docs/assess/metrics/accounting/api-financial-metrics.md
  docs/assess/metrics/accounting/api-marketing-metrics.md
  docs/assess/metrics/accounting/overview.md
  docs/assess/metrics/commerce/api-customer-retention.md
  docs/assess/metrics/commerce/api-lifetime-value.md
  docs/assess/metrics/commerce/api-orders.md
  docs/assess/metrics/commerce/api-refunds.md
  docs/assess/metrics/commerce/api-revenue.md
  docs/assess/metrics/commerce/overview.md
  docs/assess/overview.md
  docs/assess/portal/data-integrity.md
  docs/assess/portal/overview.md
  docs/assess/reports/enhanced-cash-flow-report/transactions.md
  docs/assess/reports/excel-reports.md
  docs/assess/reports/reporting-structure.md
  docs/assess/troubleshooting.md
  docs/other/user-management/sso.md
  docs/sfc/build-with-sync-for-commerce/sync-platform-selection.md
  docs/sfc/coming-soon.md
  docs/sfc/error-documentation.md
  docs/sfc/sync-for-commerce-faqs.md
  docs/sfc/sync-for-commerce-knowledge-base/initiating-a-sync.md
  docs/sfc/sync-for-commerce-knowledge-base/sync-data-model.md
  docs/sfc/sync-for-commerce-knowledge-base/synchronization-schedule.md
  sidebars/dataModel.js
Labels: review required

#258 Add new documentation for Enhanced Invoices
  docs/assess/reports/enhanced-cash-flow-report/overview.md
  docs/assess/reports/enhanced-invoices-report/overview.md
  sidebars/assess.js
Labels: reviewed, changes needed

#240 Data type list component
  docs/auth-flow/authorize-embedded-link.md
  docs/data-model/accounting/accounting.md
  docs/data-model/all-datatypes.mdx
  docs/data-model/bank-feeds/bank-feeds.md
  docs/data-model/banking/banking.md
  docs/data-model/commerce/commerce.md
  docs/integrations/all-integrations.mdx
  docs/other/developer-resources.md
  sidebars.js
  sidebars/authFlow.js
  sidebars/dataModel.js
  src/components/global/DataTypes/dataTypes.js
  src/components/global/DataTypes/index.js
  src/components/global/DataTypes/styles.module.scss
Labels: review required

#276 updated images for use cases
  docs/usecases/summary/managing-payroll.md
  static/img/use-cases/summary-pages/6c7b9e84-bank-reconciliation.png
  static/img/use-cases/summary-pages/75fd84ed-commerce-data.png
  static/img/use-cases/summary-pages/795ecc39-managing-expenses.png
  static/img/use-cases/summary-pages/d0c6b0b7-automating-payables.png
  static/img/use-cases/summary-pages/fad7ec95-4automating-receivables.png
  static/img/use-cases/summary-pages/payroll.png
Labels: ready to merge

#275 Structure changes to Assess navigation menu
  docs/assess/banking/banking-account-balances.md
  docs/assess/banking/banking-account-inflows-and-outflows.md
  docs/assess/banking/overview.md
  docs/assess/data-integrity/api-data-integrity.md
  docs/assess/data-integrity/overview.md
  docs/assess/enhanced-cash-flow/overview.md
  docs/assess/enhanced-cash-flow/transactions.md
  docs/assess/enhanced-financials/balance-sheet-accounts.md
  docs/assess/enhanced-financials/categorize-accounts.md
  docs/assess/enhanced-financials/legacy-version/enhanced-financials-legacy/balance-sheet.md
  docs/assess/enhanced-financials/legacy-version/enhanced-financials-legacy/financials.md
  docs/assess/enhanced-financials/legacy-version/enhanced-financials-legacy/profit-and-loss.md
  docs/assess/enhanced-financials/legacy-version/reporting-structure.md
  docs/assess/enhanced-financials/overview.md
  docs/assess/enhanced-financials/profit-and-loss-accounts.md
  docs/assess/enhanced-financials/supported-account-categories.md
  docs/assess/enhanced-invoices/overview.md
  docs/assess/excel/assess-report.md
  docs/assess/excel/audit-report.md
  docs/assess/excel/overview.md
  docs/assess/portal/categorize-accounts.md
  docs/assess/reports/enhanced-invoices-report/overview.md
  docs/assess/reports/excel-reports/assess-report.md
  sidebars/assess.js
Labels: reviewed, ready to merge, conflicts
