Repository codatio/codat-docs, pull requests merged in 2023-04, with the labels that each got.

#264 Update Xero app partnerships docs
  docs/integrations/accounting/xero/accounting-xero-app-partner-guidance.md
  docs/integrations/accounting/xero/accounting-xero-setup.md
  docs/integrations/accounting/xero/accounting-xero.md
  docs/integrations/accounting/xero/xero-app-partner-program.md
  sidebars/integrations.js
Labels: reviewed, ready to merge

#280 Added basic docs
  docs/assess/guides/migration-guides/deprecation-account-categories-api.md
  docs/assess/guides/migration-guides/deprecation-account-categories-excel.md
  docs/assess/guides/migration-guides/deprecation-account-categories-portal.md
  docs/assess/guides/migration-guides/deprecation-account-categories.md
  static/img/assess/account-categorization-v2.png
  static/img/assess/account-categorization-v3.png
  static/img/assess/accounting-api-account-categorisation.png
  static/img/assess/balance-sheet.png
  static/img/assess/data-export.png
  static/img/assess/financial-ratios.png
  static/img/assess/financial-statements-excel.png
  static/img/assess/marketing-screen-assess.png
  static/img/assess/profit-and-loss.png
Labels: ready to merge

#282 Sync Health monitor
  docs/sfc/sync-for-commerce-knowledge-base/monitoring-a-sync.md
  sidebars/sync-for-expenses.js
  static/img/sync-for-commerce/0006-sync-health-ui.png
  static/img/sync-for-commerce/0007-sync-details-ui.png
  static/img/sync-for-commerce/0009-sync-push-items-ui.png
Labels: review required

#285 QBO - Delete Journal entries
  docs/integrations/accounting/netsuite/accounting-netsuite-delete-bills-billpayments.md
  docs/integrations/accounting/quickbooksonline/accounting-quickbooksonline-delete-journal-entries.md
  sidebars/integrations.js
Labels: ready to merge

#295 Edit the integrations sidebar
  sidebars/integrations.js
Labels: review required

#299 Replace underwriting with lending or loan qualification
  docs/assess/guides/loan-qualification/introduction.md
  docs/assess/guides/loan-qualification/process-loan.md
  docs/assess/guides/loan-qualification/setting-up.md
  docs/assess/guides/loan-qualification/uw-decision.md
  sidebars/assess.js
  src/components/global/Usecases/index.js
  static/img/use-cases/loan-qualification/0000-acct-categorization-modal-06-03-2023.png
  static/img/use-cases/loan-qualification/0000-categorization-screen.png
  static/img/use-cases/loan-qualification/rule-creation-screen.png
  static/img/use-cases/loan-qualification/sandbox-credentials-modal.png
  static/img/use-cases/loan-qualification/underwriting-guide-rider.png
  static/img/use-cases/loan-qualification/underwriting-guide-visual-studio-2022.png
  static/img/use-cases/loan-qualification/underwriting-swagger.png
Labels: reviewed, changes needed

#300 Reconciling bank transactions as the use case name
  src/components/global/Usecases/index.js
Labels: reviewed, changes needed

#296 Account management updates
  docs/other/portal/account-management.md
  static/img/other-guides/0012-acct-mgt-access.png
  static/img/other-guides/0013-acct-mgmt-page.png
Labels: review required

#277 Update developer-resources.md
  docs/other/developer-resources.md
Labels: ready to merge

#294 Update overview.md
  docs/sfc/overview.md
Labels: ready to merge

#283 WooCommerce - Minor fixes to the setup article
  docs/integrations/accounting/xero/accounting-xero.md
  docs/integrations/commerce/woocommerce/commerce-woocommerce-setup.md
  docs/integrations/commerce/woocommerce/commerce-woocommerce.md
  static/img/integrations/commerce/woocommerce/woocommerce-app-connection-flow.png
Labels: reviewed

#302 Publish the content on deleting Journal Entries from QBO
  sidebars/integrations.js
Labels: review required

#279 QBO Bank Feeds - document new functionality - 1
  docs/bank-feeds-api/qbo-bank-feeds/qbo-bank-feeds-push-bank-transactions.md
  docs/bank-feeds-api/qbo-bank-feeds/qbo-bank-feeds-setup.md
  docs/bank-feeds-api/qbo-bank-feeds/qbo-bank-feeds-smb-user.md
  docs/bank-feeds-api/qbo-bank-feeds/qbo-bank-feeds.md
  static/img/bank-feeds-api/qbo-bank-feeds/400590b-qbo-bank-feeds_smb-customer-steps-revised.png
Labels: reviewed

#306 Amended steps in line with PayPal UI updates
  docs/integrations/commerce/paypal/test-paypal.md
Labels: reviewed, ready to merge

#307 Adding math syntax
  package-lock.json
  package.json
Labels: reviewed, ready to merge

#310 Fixes to Set up QuickBooks Online
  docs/integrations/accounting/quickbooksonline/accounting-quickbooksonline-new-setup.md
Labels: reviewed, ready to merge, comments

#312 Add links to the API Reference and shorten the title in side nav
  docs/integrations/accounting/netsuite/accounting-netsuite-delete-bills-billpayments.md
Labels: review required

#313 Minor edits to automating payables
  docs/usecases/summary/automating-payables.md
Labels: review required

#320 fix truelayer link
  redirects.config.js
Labels: ready to merge

#314 Created single page for deleting QBO objects
  docs/integrations/accounting/quickbooksonline/accounting-quickbooksonline-delete-journal-entries.md
Labels: review required

#321 Screenshot change
  docs/auth-flow/authorize-embedded-link.md
  static/img/link/0014-embedded-link-demo.png
Labels: review required

#316 Sign up with Xero: new page
  docs/integrations/accounting/xero/xero-app-partner-program.md
  docs/integrations/accounting/xero/xero-sign-up-flow.md
  sidebars/integrations.js
  static/img/integrations/accounting/xero/0021-xero-success-redirect-url.png
Labels: review required

#329 Couple of link fixes
  docs/auth-flow/customize/set-up-webhooks.md
  docs/auth-flow/customize/use-openid-connect.md
Labels: bug

#328 Improve styling and re-order
  sidebars.js
  src/styles/components/_doc-sidebar.scss
Labels: reviewed, ready to merge

#331 Instant Auth and Instant Match note
  docs/integrations/banking/plaid/banking-plaid.md
Labels: review required

#333 Use case fast follow corrections
  docs/usecases/summary/automating-payables.md
  docs/usecases/summary/automating-receivables.md
  docs/usecases/summary/dashboarding.md
  docs/usecases/summary/integrating-commerce-data.md
  docs/usecases/summary/lending.md
  docs/usecases/summary/managing-expenses.md
  docs/usecases/summary/reconciling-bank-transactions.md
  src/components/global/Usecases/index.js
Labels: review required

#335 Fix/modified dates
  docs/using-the-api/modified-dates.md
Labels: review required

#334 Refine redirects settings pages
  docs/auth-flow/customize/set-up-redirects.md
Labels: review required

#318 Adding product update
  blog/230404-product-update-4.md
  blog/230414-product-update-5.md
Labels: reviewed, changes needed
