Repository codatio/codat-docs, pull requests merged in 2023-11, with the labels that each got.

#876 Loan writeback gif
  docs/lending/guides/loan-writeback/introduction.md
  static/img/lending/loan-writeback-general-lending-example.gif
  static/img/lending/loan-writeback-invoice-finance-example.gif
Labels: ready to merge

#868 Update accounting-quickbooksdesktop.md for new QBD connector flow
  docs/integrations/accounting/quickbooksdesktop/accounting-quickbooksdesktop.md
  docs/integrations/accounting/quickbooksdesktop/install-qbd-connector-right-networks.md
  docs/integrations/accounting/quickbooksdesktop/installing-the-quickbooks-connector.md
  docs/integrations/accounting/quickbooksdesktop/legacy/accounting-quickbooksdesktop.md
  docs/integrations/accounting/quickbooksdesktop/legacy/install-qbd-connector-right-networks.md
  docs/integrations/accounting/quickbooksdesktop/legacy/installing-the-quickbooks-connector.md
  docs/integrations/accounting/quickbooksdesktop/legacy/quickbooks-desktop-faq.md
  docs/integrations/accounting/quickbooksdesktop/legacy/quickbooks-desktop-troubleshooting.md
  docs/integrations/accounting/quickbooksdesktop/legacy/software-and-hardware-requirements.md
  docs/integrations/accounting/quickbooksdesktop/quickbooks-desktop-troubleshooting.md
  redirects.config.js
  sidebars/integrations-accounting.js
  static/img/integrations/accounting/quickbooksdesktop/NEWQBD-FileLocation.png
  static/img/integrations/accounting/quickbooksdesktop/New-QBD-Download-Connector.png
  static/img/integrations/accounting/quickbooksdesktop/NewQBD-AccessConf.png
  static/img/integrations/accounting/quickbooksdesktop/NewQBD-AppCertificate.png
  static/img/integrations/accounting/quickbooksdesktop/NewQBD-DownloadInstaller.png
  static/img/integrations/accounting/quickbooksdesktop/NewQBD-Password.png
  static/img/integrations/accounting/quickbooksdesktop/NewQBD-SuccessfulConnection.png
  static/img/integrations/accounting/quickbooksdesktop/NewQBD-UpdateSelected.png
Labels: DO NOT MERGE, draft

#886 Added loan qualification guide back to docs
  docs/get-started/overview.md
  docs/guides/overview.md
  docs/lending/guides/loan-qualification/introduction.md
  docs/lending/guides/loan-qualification/process-loan.md
  docs/lending/guides/loan-qualification/setting-up.md
  docs/lending/guides/loan-qualification/uw-decision.md
  sidebars/lending.js
  static/img/use-cases/loan-qualification/0000-acct-categorization-modal-06-03-2023.png
  static/img/use-cases/loan-qualification/0000-categorization-screen.png
  static/img/use-cases/loan-qualification/account-categorization-recategorization.png
  static/img/use-cases/loan-qualification/account-categorization-view.png
Labels: reviewed, ready to merge

#881 Update sage-50-requirements.md
  docs/integrations/accounting/sage50/sage-50-requirements.md
Labels: ready to merge

#897 Update expense-transactions - drafted state endpoint updates.md
  docs/expenses/sync-process/expense-transactions.md
Labels: ready to merge

#892 Adding new support pages
  src/pages/raise-support-ticket/index.tsx
  src/pages/raise-support-ticket/styles.module.scss
  src/pages/support/index.tsx
Labels: ready to merge

#879 add pages for building enterprise consent journey
  docs/enterprise/tech-implementation/consent.md
  docs/enterprise/tech-implementation/consent/build.md
  docs/enterprise/tech-implementation/consent/considerations.md
  docs/enterprise/tech-implementation/consent/lifecyle.md
  docs/enterprise/tech-implementation/consent/overview.md
  docs/enterprise/tech-implementation/consent/uiexamples.md
  docs/enterprise/tech-implementation/getting-started.md
  docs/enterprise/tech-overview/architecture/overview.md
  sidebars/enterprise.js
  static/img/enterprise/architecture/architecture.png
  static/img/enterprise/implementation/consent/authjourney.png
Labels: ready to merge
