Repository codatio/codat-docs, pull requests merged in 2023-07, with the labels that each got.

#543 Update sage-bank-feeds-authenticate-users-web-app.md
  docs/bank-feeds-api/sage-bank-feeds/sage-bank-feeds-authenticate-users-web-app.md
Labels: comments

#545 Xero Partner updates
  docs/bank-feeds-api/xero-bank-feeds/xero-bank-feeds-partner.md
  docs/integrations/accounting/xero/accounting-xero-app-partner-guidance.md
  docs/integrations/accounting/xero/accounting-xero-setup.md
  docs/integrations/accounting/xero/accounting-xero-test.md
  docs/integrations/accounting/xero/accounting-xero.md
  docs/integrations/accounting/xero/xero-app-partner-program.md
  docs/integrations/accounting/xero/xero-faq.md
  docs/integrations/accounting/xero/xero-sign-up-flow.md
  sidebars/bank-feeds-api.js
  sidebars/integrations.js
Labels: review required

#477 Supplemental data public docs
  docs/integrations/accounting/quickbooksonline/accounting-quickbooksonline.md
  docs/integrations/accounting/xero/accounting-xero.md
  docs/using-the-api/supplemental-data/overview.md
  docs/using-the-api/supplemental-data/usecases.md
  sidebars.js
Labels: review required

#554 Move get started pages
  docs/configure/integrations.md
  docs/core-concepts/connections.md
  docs/get-started/developer-resources.md
  docs/get-started/first-steps.md
  docs/get-started/first-ten-minutes.md
  docs/get-started/libraries.md
  docs/get-started/migration.md
  docs/get-started/office-hours.md
  docs/get-started/overview.md
  docs/index.mdx
  docs/integrations/accounting/overview.md
  docs/sync-for-expenses/sync-for-expenses-faq.md
  nav.config.js
  redirects.config.js
  sidebars.js
Labels: comments

#569 Update overview.md
  docs/using-the-api/supplemental-data/overview.md
Labels: ready to merge

#571 Data freshness pitfall update
  docs/using-the-api/queueing-data-syncs.md
Labels: review required

#595 MYOB FAQ + Reference
  docs/integrations/accounting/myob/faq-myob-accountright-live.md
  docs/integrations/accounting/myob/myob-integration-reference.md
  redirects.config.js
  sidebars/integrations.js
Labels: review required

#600 Adding isDeleted property
  docs/using-the-api/modified-dates.md
  docs/using-the-api/querying.md
  docs/using-the-api/queueing-data-syncs.md
Labels: review required

#601 Update querying.md
  docs/using-the-api/querying.md
Labels: ready to merge

#605 Questions raised to support
  docs/assess/troubleshooting.md
  docs/core-concepts/connections.md
  docs/core-concepts/integrations.md
  docs/integrations/accounting/quickbooksonline/faq-quickbooks-online.md
Labels: review required

#610 Calling out limits on BigCommerce API
  docs/integrations/commerce/bigcommerce/commerce-bigcommerce-integration-reference.md
Labels: ready to merge

#597 text update adding link to use case data types
  docs/integrations/accounting/xero/xero-faq.md
  docs/using-the-api/best-practices/implementing-a-mapping-page.md
  docs/using-the-api/optimizing-api-calls.md
  sidebars.js
  static/img/other-guides/codatmappingpageexample.png
Labels: ready to merge

#628 Feature rate limiting docs
  docs/using-the-api/rate-limits.md
  docs/using-the-api/webhooks/core-rules-types.md
Labels: comments

#629 Link best practices
  docs/auth-flow/overview.md
Labels: review required
