Repository codatio/codat-docs, pull requests merged in 2023-05, with the labels that each got.

#348 Fixing upload attachment link
  docs/sync-for-expenses/sync-process/uploading-receipts.md
Labels: reviewed, changes needed

#339 Update syncing-expenses.md
  docs/sync-for-expenses/sync-process/syncing-expenses.md
Labels: help wanted, changes needed

#308 Feature: Bill pay guide
  docs/accounting-api/guides/bill-pay/how-the-demo-app-works.md
  docs/accounting-api/guides/bill-pay/introduction.md
  docs/accounting-api/guides/bill-pay/run-demo-app-locally.md
  docs/accounting-api/guides/bill-pay/use-bill-pay-demo-app.md
  docs/usecases/summary/automating-payables.md
  sidebars/accounting-api.js
  static/img/use-cases/bill-pay/bill-pay_app-start-screen-get-started.png
  static/img/use-cases/bill-pay/bill-pay_app-view.png
  static/img/use-cases/bill-pay/bill-pay_bill-detail-dialog-renamed.png
  static/img/use-cases/bill-pay/bill-pay_bill-payment-mapping-account.png
  static/img/use-cases/bill-pay/bill-pay_intuit-developer-redirect-uri.png
  static/img/use-cases/bill-pay/bill-pay_launch-bills-portal-screen.png
  static/img/use-cases/bill-pay/bill-pay_payment-view.png
  static/img/use-cases/bill-pay/bill-pay_qbo-sandbox-company-bill-status-of-paid.png
Labels: reviewed, ready to merge

#374 Fix links to Create bank transactions endpoint
  docs/bank-feeds-api/overview.mdx
  docs/bank-feeds-api/sage-bank-feeds/sage-bank-feeds-use.md
  docs/integrations/accounting/xero/xero-faq.md
Labels: review required

#372 Minor edit to Set up the Stripe integration
  docs/integrations/commerce/stripe/commerce-stripe-setup.md
Labels: review required

#376 Fixes to the office hours page
  docs/introduction/office-hours.md
Labels: review required

#380 Remove duplicate list markers, fix table styles
  src/components/global/Api/index.css
Labels: ready to merge

#383 Adding sidebar items back in
  sidebars.js
Labels: ready to merge

#368 Updated delete sections.
  docs/integrations/accounting/netsuite/accounting-netsuite-how-deleting-bill-payments-works.md
  docs/integrations/accounting/quickbooksonline/accounting-quickbooksonline-delete-journal-entries.md
  sidebars/integrations.js
Labels: comments

#385 Adding cochat, shrink usecases on homepage
  docs/index.mdx
  nav.config.js
  src/components/global/Usecases/index.js
  src/styles/components/_cards.scss
  static/img/cochat/logo-openai-mini.png
  static/img/cochat/logo-openai.png
Labels: ready to merge

#370 Update sync-for-expenses-faq. failed transactions and expense account…
  docs/sync-for-expenses/sync-for-expenses-faq.md
Labels: reviewed, comments

#238 Feature: Invoice finance guide
  docs/guides/invoice-finance/introduction.md
  docs/guides/invoice-finance/inv-fin-decision.md
  docs/guides/invoice-finance/process-invoice.md
  docs/guides/invoice-finance/setting-up.md
  docs/guides/overview.md
  docs/usecases/summary/lending.md
  sidebars.js
  sidebars/accounting-api.js
  static/img/use-cases/invoice-finance/rider.png
  static/img/use-cases/invoice-finance/rule-creation-screen.png
  static/img/use-cases/invoice-finance/sandbox-credentials-modal.png
  static/img/use-cases/invoice-finance/visual-studio-2022.png
Labels: review required

#311 Working draft for billpay docs
  docs/index.mdx
  docs/usecases/bill-pay/bills.md
  docs/usecases/bill-pay/mapping.md
  docs/usecases/bill-pay/overview.md
  docs/usecases/bill-pay/payments.md
  docs/usecases/summary/automating-payables.mdx
  docs/usecases/summary/automating-receivables.mdx
  docs/usecases/summary/dashboarding.mdx
  docs/usecases/summary/integrating-commerce-data.mdx
  docs/usecases/summary/lending.mdx
  docs/usecases/summary/managing-expenses.mdx
  docs/usecases/summary/managing-payroll.mdx
  docs/usecases/summary/reconciling-bank-transactions.mdx
  sidebars.js
  src/components/global/Integrations/integrations.js
  src/components/global/Products/index.js
  src/components/global/Usecases/index.js
  src/styles/components/_markdown.scss
  src/styles/components/_tabs.scss
  static/img/use-cases/billpay/billPay.png
Labels: documentation

#377 Converted James general expert/product team.
  docs/introduction/office-hours.md
Labels: changes needed, conflicts

#399 Optimize auth flow refinements
  docs/auth-flow/optimize/funnel.md
  docs/auth-flow/optimize/monitor-auth-flow.md
  docs/auth-flow/optimize/optimize-the-connection-journey.md
  docs/auth-flow/optimize/platform-selection.md
  docs/auth-flow/optimize/privacy.md
  docs/auth-flow/optimize/value-exchange.md
Labels: changes needed

#404 Remove pages duplicated OAS content
  docs/assess/enhanced-cash-flow/overview.md
  docs/assess/enhanced-financials/balance-sheet-accounts.md.off
  docs/assess/enhanced-financials/overview.md
  docs/assess/enhanced-financials/profit-and-loss-accounts.md.off
  docs/assess/enhanced-invoices/overview.md
  sidebars/assess.js
Labels: changes needed

#402 New Xero Bank Feeds integration
  docs/bank-feeds-api/overview.mdx
  docs/bank-feeds-api/qbo-bank-feeds/qbo-bank-feeds-push-bank-transactions.md
  docs/bank-feeds-api/xero-bank-feeds/xero-bank-feeds-push-bank-transactions.md
  docs/bank-feeds-api/xero-bank-feeds/xero-bank-feeds-setup.md
  docs/bank-feeds-api/xero-bank-feeds/xero-bank-feeds-smb-user.md
  docs/bank-feeds-api/xero-bank-feeds/xero-bank-feeds.md
  docs/integrations/bankfeeds/overview.md
  sidebars/bank-feeds-api.js
  sidebars/integrations.js
  src/components/global/Integrations/integrations.js
  static/img/bank-feeds-api/xero-bank-feeds/xero-bank-feeds-flow-amended.png
  static/img/bank-feeds-api/xero-bank-feeds/xero-bank-feeds_account-mapping-ui-manage-feed-connections.png
  static/img/bank-feeds-api/xero-bank-feeds/xero-bank-feeds_annotated-manage-connected-accounts.png
Labels: reviewed, ready to merge

#412 Dynamics 365: Document license requirement
  docs/integrations/accounting/dynamics365businesscentral/accounting-dynamics365businesscentral-setup.md
Labels: ready to merge

#424 Static oas references
  src/pages/accounting-api/index.tsx
  src/pages/assess-api/index.tsx
  src/pages/bank-feeds-api/index.tsx
  src/pages/banking-api/index.tsx
  src/pages/codat-api/index.tsx
  src/pages/commerce-api/index.tsx
  src/pages/files-api/index.tsx
  src/pages/sync-for-commerce-api/index.tsx
  src/pages/sync-for-expenses-api/index.tsx
Labels: ready to merge

#426 Removed all reference to domain discovery program
  docs/integrations/commerce/chargebee/commerce-chargebee-use.md
  docs/integrations/commerce/chargebee/commerce-chargebee.md
  docs/integrations/commerce/chargify/commerce-chargify-use.md
  docs/integrations/commerce/chargify/commerce-chargify.md
  docs/integrations/commerce/domain-discovery-program.md
  docs/integrations/commerce/overview.md
  docs/integrations/commerce/recurly/commerce-recurly-use.md
  docs/integrations/commerce/recurly/commerce-recurly.md
  sidebars/integrations.js
Labels: changes needed
