Repository codatio/codat-docs, pull requests merged in 2024-03, with the labels that each got.

#1034 Lending: Banking file upload
  docs/lending/features/bank-statements-overview.md
  docs/lending/functions/data-upload.md
  sidebars/lending.js
Labels: DO NOT MERGE

#1051 Update 240305-xero-bankstatement-report.md
  blog/240305-xero-bankstatement-report.md
Labels: comments

#1069 Update products-and-services-descriptions-lending+support.md
  docs/configure/plans/products-and-services-descriptions.md
Labels: ready to merge
