Repository codatio/codat-docs, pull requests merged in 2024-05, with the labels that each got.

#1159 Update company limit
  docs/configure/create-account.md
Labels: comments

#1147 Connection management
  docs/auth-flow/authorize-embedded-link.md
  docs/auth-flow/optimize/connection-management.md
  docs/auth-flow/overview.md
  static/img/auth-flow/auth-flow-connection-ui-examples.png
Labels: review required

#1157 Update xero-bank-feeds-push-bank-transactions.md
  docs/integrations/bank-feeds/xero-bank-feeds/xero-bank-feeds-push-bank-transactions.md
Labels: ready to merge

#1173 Removed items, added bankAccountRef
  docs/expenses/sync-process/expense-transactions.md
  docs/expenses/sync-process/reimbursable-expense-transactions.md
Labels: DO NOT MERGE, comments
